Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Gateway:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: t2.micro
      Name: gateway
      SubnetId: !ImportValue vpc-PublicSubnet
