Resources:
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole

  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ServiceRole: !Ref BatchServiceRole
      State: ENABLED
      Type: MANAGED
      ComputeResources:
        MaxvCpus: 128
        MinvCpus: 0
        Subnets:
          - !ImportValue cloud9-vpc-PrivateSubnet
        InstanceRole: !Ref InstanceProfile
        ImageId: ami-0bf2fb355727b7faf
        Type: SPOT
        InstanceTypes:
          - c5.4xlarge
        SpotIamFleetRole: !Ref SpotFleetRole
        Ec2KeyPair: gateway
        SecurityGroupIds:
          - !ImportValue cloud9-vpc-SecurityGroup

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - cloud9-instance-InstanceRole-5GDPCUMFEBWW

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnvironment
          Order: 1
      Priority: 1
      State: ENABLED
