Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Gateway:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: t2.nano
      Name: gateway
      SubnetId: !ImportValue cloud9-vpc-PublicSubnet

Outputs:
  InstanceId:
    Value: i-02c5ae0949e54748e
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"
