Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AutoStopFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: autostop.lambda_handler
      CodeUri: ../functions/autostop.py
      Runtime: python3.6
      Events:
        Watch:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ec2
              resources:
                - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-02c5ae0949e54748e'
              detail:
                state:
                  - stopping
      Policies:
        - AmazonEC2FullAccess

  ECSAssignPrivateDomain:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ecs_assign_private_domain.lambda_handler
      CodeUri: ../functions/ecs_assign_private_domain.py
      Runtime: python3.6
      Events:
        Watch:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ecs
              detail-type:
                - 'ECS Task State Change'
              detail:
                lastStatus:
                  - PENDING
                desiredStatus:
                  - RUNNING
      Policies:
        - AmazonEC2FullAccess
        - AmazonEC2ContainerServiceFullAccess
        - AmazonRoute53FullAccess
