Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AutoStopFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: autostop.lambda_handler
      CodeUri: ../functions/autostop.py
      Runtime: python3.6
      Events:
        Watch:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ec2
              resources:
                - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-09922a320ef961d86'
              detail:
                state:
                  - stopping
      Policies:
        - AmazonEC2FullAccess
