AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-9d0d7fe2
      InstanceType: p2.xlarge
      KeyName: gateway
      SecurityGroupIds:
        - !ImportValue "cloud9-vpc-SecurityGroup"
      SubnetId: !ImportValue "cloud9-vpc-PrivateSubnet"
      IamInstanceProfile: !Ref InstanceProfile

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  InstanceRoleS3FullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Full
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "s3:*"

  InstanceRoleAthenaFullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AthenaFull
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "athena:*"
              - "glue:getTable"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue "cloud9-vpc-HostedZone"
      Name: gpu.cloud9
      Type: A
      TTL: 300
      ResourceRecords:
        - !GetAtt Instance.PrivateIp
