AWSTemplateFormatVersion: '2010-09-09'

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              Service:
                - ec2.amazonaws.com
                - ecs.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
            Effect: Allow
      Path: /

  InstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2Full
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "ec2:*"
              - "ecs:*"
              - "autoscaling:*"
              - "elasticloadbalancing:*"
              - "application-autoscaling:*"
              - "cloudwatch:*"
              - "logs:*"
              - "s3:*"
              - "athena:*"
              - "glue:*"
              - "cloudformation:*"
              - "dynamodb:*"
              - "iam:*"
              - "cloudfront:*"
              - "eks:*"
              - "lambda:*"
              - "sqs:*"
              - "batch:*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  InstanceRoleArn:
    Value: !GetAtt InstanceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-InstanceRoleArn"
