AWSTemplateFormatVersion: '2010-09-09'

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              Service:
                - ec2.amazonaws.com
                - ecs.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
            Effect: Allow
      Path: /

  InstanceRoleEC2FullAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2Full
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "ec2:*"

  InstanceRoleS3FullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Full
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "s3:*"

  InstanceRoleAthenaFullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AthenaFull
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "athena:*"
              - "glue:getTable"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  InstanceRoleArn:
    Value: !GetAtt InstanceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-InstanceRoleArn"
