AWSTemplateFormatVersion: '2010-09-09'

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  InstanceRoleS3FullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Full
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "s3:*"

  InstanceRoleAthenaFullPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AthenaFull
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - "athena:*"
              - "glue:getTable"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
